-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Wheelyjoe's Weapons Damage Mod updated by Ghosti to support cluster munitions
--
-- This configuration is tailored for a mission generated by DCS Liberation
-- see https://github.com/dcs-liberation/dcs_liberation
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- SplashDamage plugin - configuration
env.info("DCSLiberation|SplashDamage plugin - configuration")

if dcsLiberation then
    env.info("DCSLiberation|SplashDamage plugin - dcsLiberation")

    -- specific options
    local bdaMessages = false
    local clusterEffects = false
    local shipRadarDamage = false

    -- retrieve specific options values
    if dcsLiberation.plugins then
        env.info("DCSLiberation|SplashDamage plugin - dcsLiberation.plugins")
    
        if dcsLiberation.plugins.splashdamage then
            env.info("DCSLiberation|SplashDamage plugin - dcsLiberation.plugins.SplashDamage")
            bdaMessages = dcsLiberation.plugins.splashdamage.bdaMessages
            env.info(string.format("DCSLiberation|SplashDamage plugin - bdaMessages = %s",tostring(bdaMessages)))

            clusterEffects = dcsLiberation.plugins.splashdamage.clusterEffects
            env.info(string.format("DCSLiberation|SplashDamage plugin - clusterEffects = %s",tostring(clusterEffects)))

            shipRadarDamage = dcsLiberation.plugins.splashdamage.shipRadarDamage
            env.info(string.format("DCSLiberation|SplashDamage plugin - shipRadarDamage = %s",tostring(shipRadarDamage)))
        end
    end
    
    -- actual configuration code    
    weaponDamage(bdaMessages, clusterEffects, shipRadarDamage)

end